# Generated by Django 2.1.4 on 2018-12-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Promo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Image name'),
        ),
    ]
