# Generated by Django 2.1.4 on 2018-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_in_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exclusive',
            field=models.BooleanField(default=False, verbose_name='Exclusive'),
        ),
    ]
