# Generated by Django 2.1.4 on 2018-12-24 09:43
from json import load as jload
from django.db import migrations


def create_categories(apps, schema_editor):
    model_class = apps.get_model('products.category')
    with open('products/fixtures/categories.json', 'r') as jf:
        for c in jload(jf):
            model_class.objects.create(
                name=c.get('name')
            )


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0007_auto_20181224_0941'),
    ]

    operations = [
        migrations.RunPython(
            create_categories,
            lambda x, y: (x, y)

        )
    ]
