# Generated by Django 2.1.4 on 2018-12-19 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1900-1234-5678'.", regex='^(\\d{4})(-?\\d{4}){2}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
