# Generated by Django 2.1.4 on 2018-12-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('img_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.Img')),
                ('value', models.ImageField(unique=True, upload_to='avatars/', verbose_name='Avatar')),
            ],
            bases=('images.img',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('img_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.Img')),
                ('value', models.ImageField(unique=True, upload_to='products/', verbose_name='Image')),
            ],
            bases=('images.img',),
        ),
    ]
