# Generated by Django 2.1.4 on 2018-12-24 12:15

from django.db import migrations
from django.conf import settings
import os


def load_product_images(apps, scheme_editor):
    model_class = apps.get_model('images.ProductImage')
    for img in os.listdir(os.path.join(settings.MEDIA_ROOT, 'products')):
        model_class.objects.create(
            name=img,
            value=os.path.join('products', img)
        )

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            load_product_images,
            lambda x, y: (x, y)

        )
    ]
